version: '3'

volumes:
  mongo_data: null

networks:
  mern_network:
    driver: bridge

services:
    mongo:
      container_name: mern-mongo-db
      image: mongo:latest
      restart: always     
      volumes:
          - mongo_data:/data/db
      networks:
        - mern_network
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root

    mongo-express:
      image: mongo-express
      restart: always
      ports:
      - 8086:8081
      networks:
      - mern_network
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root

    backend:
      build: ./app/
      ports:
        - "6200:6200"
      volumes:
        - ./app:/usr/src/app
        - /usr/src/app/node_modules
      depends_on:
        - mongo
      networks:
        - mern_network        

#    frontend:
#      build: ./web/
#      ports:
#        - "3000:3000"
#      volumes:
#        - ./web:/usr/src/app      
#      depends_on:
#        - backend